# Generated by Django 4.2.1 on 2023-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_path',
            field=models.CharField(blank=True, max_length=1000, verbose_name='image path'),
        ),
    ]
