# Generated by Django 4.2.1 on 2023-05-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customuser_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
