# Generated by Django 4.2.1 on 2023-05-21 13:20

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_changepasswordrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepasswordrequest',
            name='code',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
