# Generated by Django 4.2.1 on 2023-05-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_changepasswordrequest_reqtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='changepasswordrequest',
            name='reqtime',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
    ]
