# Generated by Django 4.2.1 on 2023-05-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgamesbase',
            name='year',
            field=models.IntegerField(),
        ),
    ]
