# Generated by Django 4.2.1 on 2023-05-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0005_guilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='guilds',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guilds',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
